{% set name = "azure-mgmt-containerinstance" %}
{% set version = "10.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/azure-mgmt-containerinstance-{{ version }}.zip
  sha256: 78d437adb28574f448c838ed5f01f9ced378196098061deb59d9f7031704c17e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    # bumping to 3.8 to avoid typing-extensions
    - python >={{ python_min }}
    - isodate <1.0.0,>=0.6.1
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2,<2.0.0

test:
  imports:
    - azure.mgmt.containerinstance
    - azure.mgmt.containerinstance.models
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Container Instance Client Library for Python
  description: |
    This is the Microsoft Azure Container Instance Client Library.

    Azure Resource Manager (ARM) is the next generation of management APIs that
    replace the old Azure Service Management (ASM).
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://docs.microsoft.com/en-us/azure/developer/python/

extra:
  recipe-maintainers:
    - xylar
