schema_version: 1

context:
  name: azure-mgmt-containerinstance
  version: 10.2.0b1


package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_mgmt_containerinstance-${{ version }}.tar.gz
  sha256: bf4bb77bd6681270dd0a733aa3a7c3ecdfacba8e616d3a8c3b98cce9c48cc7c0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - isodate <1.0.0,>=0.6.1
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - typing-extensions >=4.6.0

tests:
  - python:
      imports:
        - azure.mgmt.containerinstance
        - azure.mgmt.containerinstance.models
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Microsoft Azure Container Instance Client Library for Python
  description: |
    This is the Microsoft Azure Container Instance Client Library.

    Azure Resource Manager (ARM) is the next generation of management APIs that
    replace the old Azure Service Management (ASM).
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/Azure/azure-sdk-for-python
  repository: https://github.com/Azure/azure-sdk-for-python
  documentation: https://docs.microsoft.com/en-us/azure/developer/python/

extra:
  recipe-maintainers:
    - xylar
    - janjagusch
